#!/usr/bin/env python
##!/home/vagrant/myve/bin/python

import os
import ConfigParser as cp
import sys
import inspect
import argcomplete
import logging


logging.basicConfig(filename='pyexpo.log', level=logging.DEBUG)


logger = logging.getLogger(__name__)


expo_location = '~/projects/py'
sys.path.insert(0, os.path.expanduser(expo_location))
from expo import translator

current_dir = os.path.dirname(os.path.abspath(__file__))
home_cfg = os.path.join(current_dir, '.pyexpo')

cfgparser = cp.ConfigParser()
logger.debug("trying to read configuration from file...")
cfgparser.read([home_cfg])
pkg_path = os.path.abspath(os.path.expanduser(cfgparser.get('package1', 'path')))

pkg_paths = [pkg_path, ]
parser = translator.build_parser(pkg_paths)
logger.debug("parser is built")

#logger.debug("before autocomplete call...")
argcomplete.autocomplete(parser)
#with open('/home/vagrant/pyexpo-output', 'w') as w:
#    w.write('!')

namespace = parser.parse_args()
namespace.__call(namespace)
